#Read Me#

#By running this program, we can use TPM.txt which is generated by .fastq 
#from each sample, to compare with the cancer-related gene set.

#1. project_path is the folder will save the output files
#2. sample_path is the folder of TPM.txt file for each sample
#3. reference_path is the cancer-related gene sets of 17 types of cancer

#INPUT: TPM.txt from sample
#       *.xml frem cancer-related gene set



project_path=/Users/annlyuan2018/Downloads/test
sample_path=/Users/annlyuan2018/Downloads/exp_sample
reference_path=/Users/annlyuan2018/Downloads/cancer_reference


for j in $(cd $sample_path;ls *.txt); do

	Name=$(basename $sample_path/$j .txt)
	 
	 mkdir $project_path/$Name

	 #touch $result_path/$Name/total_$Name.txt
  
   for i in $(cd $reference_path;ls *.xml); do

   	 Cancer=$(basename $reference_path/$i .xml)

     mkdir $project_path/$Name/$Cancer

     awk '$2!='0\n' {print $1}' $sample_path/$j> $project_path/$Name/$Cancer/exp.txt
     awk '$2>=1 {print $1}' $sample_path/$j> $project_path/$Name/$Cancer/exp1.txt

     grep "<identifier" $reference_path/$i | awk '{print $2}' > $project_path/$Name/$Cancer/$Cancer.txt
     sed -i '' 's/^.\{4\}//g' $project_path/$Name/$Cancer/$Cancer.txt
     sed -i '' 's/.\{1\}$//g' $project_path/$Name/$Cancer/$Cancer.txt

     grep -F -f $project_path/$Name/$Cancer/$Cancer.txt $project_path/$Name/$Cancer/exp.txt > $project_path/$Name/$Cancer/same_$Cancer.txt
     wc -l $project_path/$Name/$Cancer/$Cancer.txt $project_path/$Name/$Cancer/exp.txt $project_path/$Name/$Cancer/same_$Cancer.txt > $project_path/$Name/$Cancer/results_$Cancer.txt
     grep -F -f $project_path/$Name/$Cancer/$Cancer.txt $project_path/$Name/$Cancer/exp1.txt > $project_path/$Name/$Cancer/same1_$Cancer.txt
     wc -l $project_path/$Name/$Cancer/$Cancer.txt $project_path/$Name/$Cancer/exp1.txt $project_path/$Name/$Cancer/same1_$Cancer.txt >>$project_path/$Name/$Cancer/results_$Cancer.txt

     awk '{print $1}' $project_path/$Name/$Cancer/results_$Cancer.txt | xargs |awk -v t=$Cancer '{print t,$1,$2,$3,$5,$6,$7}'>> $project_path/total_$Name.txt

   done

     #awk -v r=$(seq 1 $(ls $reference_path/*.xml|wc -l)) '{print r}' $project_path/total_$Name.txt>> $project_path/total_$Name.txt

done






