#Read Me#

#By running this program, we can use TPM.txt which is generated by .fastq 
#from each sample, to compare with the cancer-related gene set.

#1. project_path is the folder will save the output files
#2. sample_path is the folder of TPM.txt file for each sample
#3. reference_path is the cancer-related gene sets of 17 types of cancer

#INPUT: TPM.txt from sample
#       *.xml frem cancer-related gene set

#pattern:
####    bash cancer_analysis_f.sh 16 ./exp_sample ./cancer_reference ./test

TPM_threshould=${4:-16}

echo "TPM_threshould is  $TPM_threshould"

sample_path=$1
reference_path=$2
project_path=$3


#project_path=/Users/annlyuan2018/Downloads/test
#sample_path=/Users/annlyuan2018/Downloads/exp_sample
#reference_path=/Users/annlyuan2018/Downloads/cancer_reference
#code_path=/Users/annlyuan2018/Downloads/R_code

#TPM_threshould=16

for j in $(cd $sample_path;ls *.counts); do

	Nam=$(basename $sample_path/$j .counts)
	 
	   mkdir -p $project_path/$Nam
	 
	    awk '{print $1,$6,$7}' $sample_path/$j|tail -n +3 > $project_path/$Nam/union.txt

        Rscript $reference_path/counts_to_TPM0.R $project_path/$Nam/union.txt $project_path/$Nam/unionTPM.txt
  
   for i in $(cd $reference_path;ls *.xml); do

   	     Cancer=$(basename $reference_path/$i .xml)

         mkdir -p $project_path/$Nam/$Cancer

         awk '$2>'$TPM_threshould' {print $1}' $project_path/$Nam/unionTPM.txt> $project_path/$Nam/$Cancer/exp.txt

         grep "<identifier" $reference_path/$i | awk '{print $2}' > $project_path/$Nam/$Cancer/$Cancer.txt
         sed -i '' 's/^.\{4\}//g' $project_path/$Nam/$Cancer/$Cancer.txt
         sed -i '' 's/.\{1\}$//g' $project_path/$Nam/$Cancer/$Cancer.txt

         grep -F -f $project_path/$Nam/$Cancer/$Cancer.txt $project_path/$Nam/$Cancer/exp.txt > $project_path/$Nam/$Cancer/same_$Cancer.txt
         wc -l $project_path/$Nam/$Cancer/$Cancer.txt $project_path/$Nam/$Cancer/exp.txt $project_path/$Nam/$Cancer/same_$Cancer.txt > $project_path/$Nam/$Cancer/results_$Cancer.txt
     
         awk '{print $1}' $project_path/$Nam/$Cancer/results_$Cancer.txt | xargs |awk -v t=$Cancer '{print t,$1,$2,$3}'>> $project_path/total_$Nam.txt

         #awk '{print ($4/$2)*100}' $project_path/total_$Nam.txt > $project_path/t.txt
         #paste $project_path/total_$Nam.txt $project_path/t.txt > $project_path/total2_$Nam.txt
         #rm -f $project_path/t.txt
         
         #awk -v t=$Cancer '{print}BEGIN{print t}' $project_path/$Nam/$Cancer/total_$Cancer.txt >>$project_path/total_$Nam.txt

   done

         awk '{print ($4/$2)*100}' $project_path/total_$Nam.txt > $project_path/t.txt
         paste $project_path/total_$Nam.txt $project_path/t.txt > $project_path/total2_$Nam.txt
         rm -f $project_path/t.txt $project_path/total_$Nam.txt
     #awk -v r=$(seq 1 $(ls $reference_path/*.xml|wc -l)) '{print r}' $project_path/total_$Nam.txt>> $project_path/total_$Nam.txt

done
        
         







